### ISSUE TITLE
Segmentation fault after WebSocket connection

### ISSUE THREAD

**Issue by jwindgassen** [Kitware/trame#159]
Continuation of #145!

I am currently trying to run trame/pv-visualizer on our JupyterLab instance using a [JupyterServerProxy](https://jupyter-server-proxy.readthedocs.io/en/latest/)
After starting the proxy, the webpage is loading properly for a few seconds. But after that, the UI can only be seen for a frame before the connection is lost.

```
[I 2022-11-24 23:40:44.960 SingleUserNotebookApp handlers:446] Trying to establish websocket connection to ws://localhost:54753/ws
[I 2022-11-24 23:40:44.963 SingleUserNotebookApp handlers:453] Websocket connection established to ws://localhost:54753/ws

Loguru caught a signal: SIGSEGV
Stack trace:
85            0x4006ce _start + 46
84      0x14dd31dbbcf3 __libc_start_main + 243
83      0x14dd3363fc29 Py_BytesMain + 41
82      0x14dd33660166 Py_RunMain + 326
81      0x14dd3364cb0c PyRun_SimpleStringFlags + 60
80      0x14dd335cd424 PyRun_StringFlags + 164
79      0x14dd3364fc57 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x1b9c57) [0x14dd3364fc57]
78      0x14dd33651974 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x1bb974) [0x14dd33651974]
77      0x14dd335b129b PyEval_EvalCode + 27
76      0x14dd335b12e3 PyEval_EvalCodeEx + 67
75      0x14dd335b1341 _PyEval_EvalCodeWithName + 81
74      0x14dd335b1534 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x11b534) [0x14dd335b1534]
73      0x14dd335b4302 _PyEval_EvalFrameDefault + 7394
72      0x14dd335c168d _PyFunction_Vectorcall + 221
71      0x14dd335b1534 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x11b534) [0x14dd335b1534]
70      0x14dd335b70fd _PyEval_EvalFrameDefault + 19165
69      0x14dd335cb2aa PyVectorcall_Call + 170
68      0x14dd335cac59 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x134c59) [0x14dd335cac59]
67      0x14dd335c168d _PyFunction_Vectorcall + 221
66      0x14dd335b1534 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x11b534) [0x14dd335b1534]
65      0x14dd335b70fd _PyEval_EvalFrameDefault + 19165
64      0x14dd335cb2aa PyVectorcall_Call + 170
63      0x14dd335c168d _PyFunction_Vectorcall + 221
62      0x14dd335b1534 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x11b534) [0x14dd335b1534]
61      0x14dd335b70fd _PyEval_EvalFrameDefault + 19165
60      0x14dd335cb2aa PyVectorcall_Call + 170
59      0x14dd335c168d _PyFunction_Vectorcall + 221
58      0x14dd335b1534 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x11b534) [0x14dd335b1534]
57      0x14dd335b2b7f _PyEval_EvalFrameDefault + 1375
56      0x14dd335c168d _PyFunction_Vectorcall + 221
55      0x14dd335b1534 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x11b534) [0x14dd335b1534]
54      0x14dd335b2d29 _PyEval_EvalFrameDefault + 1801
53      0x14dd335c1923 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x12b923) [0x14dd335c1923]
52      0x14dd335b2d29 _PyEval_EvalFrameDefault + 1801
51      0x14dd335c1923 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x12b923) [0x14dd335c1923]
50      0x14dd335b2d29 _PyEval_EvalFrameDefault + 1801
49      0x14dd335c1923 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x12b923) [0x14dd335c1923]
48      0x14dd335b2d29 _PyEval_EvalFrameDefault + 1801
47      0x14dd335c1923 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x12b923) [0x14dd335c1923]
46      0x14dd335b85b3 _PyEval_EvalFrameDefault + 24467
45      0x14dd335ba75a /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x12475a) [0x14dd335ba75a]
44      0x14dd336385c6 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x1a25c6) [0x14dd336385c6]
43      0x14dd335bb8c3 _PyObject_MakeTpCall + 131
42      0x14dd229ae378 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/lib-dynload/_asyncio.cpython-39-x86_64-linux-gnu.so(+0x8378) [0x14dd229ae378]
41      0x14dd229ac8f4 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/python3.9/lib-dynload/_asyncio.cpython-39-x86_64-linux-gnu.so(+0x68f4) [0x14dd229ac8f4]
40      0x14dd335e6032 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x150032) [0x14dd335e6032]
39      0x14dd335b4d6c _PyEval_EvalFrameDefault + 10060
38      0x14dd335e6032 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x150032) [0x14dd335e6032]
37      0x14dd335b4d6c _PyEval_EvalFrameDefault + 10060
36      0x14dd335e6032 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x150032) [0x14dd335e6032]
35      0x14dd335b4d6c _PyEval_EvalFrameDefault + 10060
34      0x14dd335e6032 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x150032) [0x14dd335e6032]
33      0x14dd335b70fd _PyEval_EvalFrameDefault + 19165
32      0x14dd335c168d _PyFunction_Vectorcall + 221
31      0x14dd335b1534 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x11b534) [0x14dd335b1534]
30      0x14dd335b2d29 _PyEval_EvalFrameDefault + 1801
29      0x14dd335c168d _PyFunction_Vectorcall + 221
28      0x14dd335b1534 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x11b534) [0x14dd335b1534]
27      0x14dd335b2d29 _PyEval_EvalFrameDefault + 1801
26      0x14dd335c1923 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x12b923) [0x14dd335c1923]
25      0x14dd335b48a4 _PyEval_EvalFrameDefault + 8836
24      0x14dd335bb8c3 _PyObject_MakeTpCall + 131
23      0x14dd335cc4a0 /p/software/juwels/stages/2022/software/Python/3.9.6-GCCcore-11.2.0/lib/libpython3.9.so.1.0(+0x1364a0) [0x14dd335cc4a0]
22      0x14dcd16fa3cd /p/usersoftware/swmanage/goebbert1/stage2022/ParaView/easybuild/juwels/software/ParaView/5.11.0-gpsmkl-2021b/lib64/python3.9/site-packages/paraview/modules/vtkPVClientWeb.so(+0x43cd) [0x14dcd16fa3cd]
21      0x14dcd16ee191 vtkPVWebApplication::StillRenderToBuffer(vtkSMViewProxy*, unsigned long, int) + 17
20      0x14dcd16eddc2 vtkPVWebApplication::StillRender(vtkSMViewProxy*, int) + 370
19      0x14dd0050c011 vtkSMViewProxy::CaptureWindow(int, int) + 81
18      0x14dd0050ba76 /p/usersoftware/swmanage/goebbert1/stage2022/ParaView/easybuild/juwels/software/ParaView/5.11.0-gpsmkl-2021b/lib/libvtkRemotingViews-pv5.11.so.1(+0x2eca76) [0x14dd0050ba76]
17      0x14dd0050b675 /p/usersoftware/swmanage/goebbert1/stage2022/ParaView/easybuild/juwels/software/ParaView/5.11.0-gpsmkl-2021b/lib/libvtkRemotingViews-pv5.11.so.1(+0x2ec675) [0x14dd0050b675]
16      0x14dd0050ae24 vtkSMViewProxy::CaptureWindowSingle(int, int) + 52
15      0x14dd0050a7a2 vtkSMViewProxy::CaptureWindowInternal(int, int) + 770
14      0x14dd0050a21a vtkSMViewProxy::StillRender() + 362
13      0x14dd04e03764 vtkPVSessionBase::ExecuteStream(unsigned int, vtkClientServerStream const&, bool) + 52
12      0x14dd04e0585b vtkPVSessionCore::ExecuteStreamInternal(vtkClientServerStream const&, bool) + 251
11      0x14dd2237257d vtkClientServerInterpreter::ProcessStream(vtkClientServerStream const&) + 29
10      0x14dd223720ed vtkClientServerInterpreter::ProcessOneMessage(vtkClientServerStream const&, int) + 221
9       0x14dd22371fae vtkClientServerInterpreter::ProcessCommandInvoke(vtkClientServerStream const&, int) + 1214
8       0x14dcfd8a3950 vtkPVRenderViewCommand(vtkClientServerInterpreter*, vtkObjectBase*, char const*, vtkClientServerStream const&, vtkClientServerStream&, void*) + 6608
7       0x14dd0043c977 vtkPVRenderView::StillRender() + 103
6       0x14dd00449fc5 vtkPVRenderView::Render(bool, bool) + 2373
5       0x14dd0477b920 vtkXOpenGLRenderWindow::Render() + 32
4       0x14dd046ceb99 vtkOpenGLRenderWindow::Render() + 169
3       0x14dd0572ed68 vtkRenderWindow::Render() + 584
2       0x14dd0436e779 vtkXRenderWindowInteractor::Initialize() + 217
1       0x14dd07cf689b XSync + 11
0       0x14dd32ad9ce0 /usr/lib64/libpthread.so.0(+0x12ce0) [0x14dd32ad9ce0]
(  16.615s) [paraview        ]                       :0     FATL| Signal: SIGSEGV
/p/home/jusers/windgassen1/juwels/Nek/proxy-venv/lib/python3.9/site-packages/jupyter_trame_proxy/share/launch_trame.sh: line 20: 16088 Segmentation fault      python -c "from pv_visualizer.app.main import main; main(port=$1)"
2022-11-24 23:40:47,646 - SingleUserNotebookApp - ERROR - Uncaught exception GET /user/j.windgassen_at_fz-juelich.de/vf0a98375c2247efb8baa17a2ed3d3ce/trame/ws (79.232.197.221)
HTTPServerRequest(protocol='https', host='jupyter-jsc.fz-juelich.de', method='GET', uri='/user/j.windgassen_at_fz-juelich.de/vf0a98375c2247efb8baa17a2ed3d3ce/trame/ws', version='HTTP/1.1', remote_ip='79.232.197.221')
Traceback (most recent call last):
  File "/p/software/juwels/stages/2022/software/Jupyter/2022.3.4-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/tornado/websocket.py", line 1086, in write_message
    fut = self._write_frame(True, opcode, message, flags=flags)
  File "/p/software/juwels/stages/2022/software/Jupyter/2022.3.4-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/tornado/websocket.py", line 1061, in _write_frame
    return self.stream.write(frame)
  File "/p/software/juwels/stages/2022/software/Jupyter/2022.3.4-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/tornado/iostream.py", line 530, in write
    self._check_closed()
  File "/p/software/juwels/stages/2022/software/Jupyter/2022.3.4-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/tornado/iostream.py", line 1019, in _check_closed
    raise StreamClosedError(real_error=self.error)
tornado.iostream.StreamClosedError: Stream is closed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/p/software/juwels/stages/2022/software/Jupyter/2022.3.4-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/tornado/websocket.py", line 635, in _run_callback
    result = callback(*args, **kwargs)
  File "/p/software/juwels/stages/2022/software/Jupyter/2022.3.4-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/jupyter_server_proxy/handlers.py", line 160, in on_message
    self.ws.write_message(message, binary=isinstance(message, bytes))
  File "/p/software/juwels/stages/2022/software/Jupyter/2022.3.4-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/tornado/websocket.py", line 1500, in write_message
    return self.protocol.write_message(message, binary=binary)
  File "/p/software/juwels/stages/2022/software/Jupyter/2022.3.4-gcccoremkl-11.2.0-2021.4.0/lib/python3.9/site-packages/tornado/websocket.py", line 1088, in write_message
    raise WebSocketClosedError()
tornado.websocket.WebSocketClosedError
```
<img width="1440" alt="Screenshot 2022-11-24 at 23 50 47" src="https://user-images.githubusercontent.com/75307755/203871789-9dccb847-76d3-4934-b31e-b73cc1480e40.png">

I tried digging around in the code for an afternoon and finding out, where it goes south, but couldn't find anything. I was previously using ParaView 5.9 and Python 3.8 (i modified the code a bit to run there) and blamed it on those versions, but we just installed ParaView 5.11 and this error still occurs there with Python 3.9

**Comment by jourdain** [comment]
It seems that you are using a ParaView that expect X but you probably don't have it running. In such case, you need to use the EGL or OSMesa build of ParaView.

**Comment by jwindgassen** [comment]
That solved it, ty!

**Comment by wizztjh** [comment]
@jwindgassen How do you solve it? Can you share the setup?
