### ISSUE TITLE
vtkRemoteView not working. wslink ConnectionResetError: Cannot write to closing transport. Memory usage grows indefinitely.

### ISSUE THREAD

**Issue by phcerdan** [Kitware/trame#474]
**Describe the bug**

vtkLocalView works well, but changing to vtkRemoteView doesn't.

**To Reproduce**

1. Go to https://github.com/Kitware/trame-tutorial.git
2. Use 04_vtk/solution.py
3. Swap usage of vtkRemoteView (the default is vtkLocalView), or even clearer, swap to vtkRemoteLocalView

***Code***

```python
import os

from trame.app import get_server
from trame.ui.vuetify import SinglePageWithDrawerLayout
from trame.widgets import vtk, vuetify

from trame_vtk.modules.vtk.serializers import configure_serializer

from vtkmodules.vtkCommonDataModel import vtkDataObject
from vtkmodules.vtkFiltersCore import vtkContourFilter
from vtkmodules.vtkIOXML import vtkXMLUnstructuredGridReader
from vtkmodules.vtkRenderingAnnotation import vtkCubeAxesActor

from vtkmodules.vtkRenderingCore import (
    vtkActor,
    vtkDataSetMapper,
    vtkRenderer,
    vtkRenderWindow,
    vtkRenderWindowInteractor,
)

# Required for interactor initialization
from vtkmodules.vtkInteractionStyle import vtkInteractorStyleSwitch  # noqa

# Required for rendering initialization, not necessary for
# local rendering, but doesn't hurt to include it
import vtkmodules.vtkRenderingOpenGL2  # noqa

CURRENT_DIRECTORY = os.path.abspath(os.path.dirname(__file__))

# Configure scene encoder
configure_serializer(encode_lut=True, skip_light=True)

# -----------------------------------------------------------------------------
# Constants
# -----------------------------------------------------------------------------


class Representation:
    Points = 0
    Wireframe = 1
    Surface = 2
    SurfaceWithEdges = 3


class LookupTable:
    Rainbow = 0
    Inverted_Rainbow = 1
    Greyscale = 2
    Inverted_Greyscale = 3


# -----------------------------------------------------------------------------
# VTK pipeline
# -----------------------------------------------------------------------------

renderer = vtkRenderer()
renderWindow = vtkRenderWindow()
renderWindow.AddRenderer(renderer)

renderWindowInteractor = vtkRenderWindowInteractor()
renderWindowInteractor.SetRenderWindow(renderWindow)
renderWindowInteractor.GetInteractorStyle().SetCurrentStyleToTrackballCamera()

# Read Data
reader = vtkXMLUnstructuredGridReader()
reader.SetFileName(os.path.join(CURRENT_DIRECTORY, "../../data/disk_out_ref.vtu"))
reader.Update()

# Extract Array/Field information
dataset_arrays = []
fields = [
    (reader.GetOutput().GetPointData(), vtkDataObject.FIELD_ASSOCIATION_POINTS),
    (reader.GetOutput().GetCellData(), vtkDataObject.FIELD_ASSOCIATION_CELLS),
]
for field in fields:
    field_arrays, association = field
    for i in range(field_arrays.GetNumberOfArrays()):
        array = field_arrays.GetArray(i)
        array_range = array.GetRange()
        dataset_arrays.append(
            {
                "text": array.GetName(),
                "value": i,
                "range": list(array_range),
                "type": association,
            }
        )
default_array = dataset_arrays[0]
default_min, default_max = default_array.get("range")

# Mesh
mesh_mapper = vtkDataSetMapper()
mesh_mapper.SetInputConnection(reader.GetOutputPort())
mesh_actor = vtkActor()
mesh_actor.SetMapper(mesh_mapper)
renderer.AddActor(mesh_actor)

# Mesh: Setup default representation to surface
mesh_actor.GetProperty().SetRepresentationToSurface()
mesh_actor.GetProperty().SetPointSize(1)
mesh_actor.GetProperty().EdgeVisibilityOff()

# Mesh: Apply rainbow color map
mesh_lut = mesh_mapper.GetLookupTable()
mesh_lut.SetHueRange(0.666, 0.0)
mesh_lut.SetSaturationRange(1.0, 1.0)
mesh_lut.SetValueRange(1.0, 1.0)
mesh_lut.Build()

# Mesh: Color by default array
mesh_mapper.SelectColorArray(default_array.get("text"))
mesh_mapper.GetLookupTable().SetRange(default_min, default_max)
if default_array.get("type") == vtkDataObject.FIELD_ASSOCIATION_POINTS:
    mesh_mapper.SetScalarModeToUsePointFieldData()
else:
    mesh_mapper.SetScalarModeToUseCellFieldData()
mesh_mapper.SetScalarVisibility(True)
mesh_mapper.SetUseLookupTableScalarRange(True)

# Contour
contour = vtkContourFilter()
contour.SetInputConnection(reader.GetOutputPort())
contour_mapper = vtkDataSetMapper()
contour_mapper.SetInputConnection(contour.GetOutputPort())
contour_actor = vtkActor()
contour_actor.SetMapper(contour_mapper)
renderer.AddActor(contour_actor)

# Contour: ContourBy default array
contour_value = 0.5 * (default_max + default_min)
contour.SetInputArrayToProcess(
    0, 0, 0, default_array.get("type"), default_array.get("text")
)
contour.SetValue(0, contour_value)

# Contour: Setup default representation to surface
contour_actor.GetProperty().SetRepresentationToSurface()
contour_actor.GetProperty().SetPointSize(1)
contour_actor.GetProperty().EdgeVisibilityOff()

# Contour: Apply rainbow color map
contour_lut = contour_mapper.GetLookupTable()
contour_lut.SetHueRange(0.666, 0.0)
contour_lut.SetSaturationRange(1.0, 1.0)
contour_lut.SetValueRange(1.0, 1.0)
contour_lut.Build()

# Contour: Color by default array
contour_mapper.SelectColorArray(default_array.get("text"))
contour_mapper.GetLookupTable().SetRange(default_min, default_max)
if default_array.get("type") == vtkDataObject.FIELD_ASSOCIATION_POINTS:
    contour_mapper.SetScalarModeToUsePointFieldData()
else:
    contour_mapper.SetScalarModeToUseCellFieldData()
contour_mapper.SetScalarVisibility(True)
contour_mapper.SetUseLookupTableScalarRange(True)

# Cube Axes
cube_axes = vtkCubeAxesActor()
renderer.AddActor(cube_axes)

# Cube Axes: Boundaries, camera, and styling
cube_axes.SetBounds(mesh_actor.GetBounds())
cube_axes.SetCamera(renderer.GetActiveCamera())
cube_axes.SetXLabelFormat("%6.1f")
cube_axes.SetYLabelFormat("%6.1f")
cube_axes.SetZLabelFormat("%6.1f")
cube_axes.SetFlyModeToOuterEdges()

renderer.ResetCamera()

# -----------------------------------------------------------------------------
# Trame setup
# -----------------------------------------------------------------------------

server = get_server(client_type="vue2")
state, ctrl = server.state, server.controller

state.setdefault("active_ui", None)

# -----------------------------------------------------------------------------
# Callbacks
# -----------------------------------------------------------------------------


@state.change("cube_axes_visibility")
def update_cube_axes_visibility(cube_axes_visibility, **kwargs):
    cube_axes.SetVisibility(cube_axes_visibility)
    ctrl.view_update()


# Selection Change
def actives_change(ids):
    _id = ids[0]
    if _id == "1":  # Mesh
        state.active_ui = "mesh"
    elif _id == "2":  # Contour
        state.active_ui = "contour"
    else:
        state.active_ui = "nothing"


# Visibility Change
def visibility_change(event):
    _id = event["id"]
    _visibility = event["visible"]

    if _id == "1":  # Mesh
        mesh_actor.SetVisibility(_visibility)
    elif _id == "2":  # Contour
        contour_actor.SetVisibility(_visibility)
    ctrl.view_update()


# Representation Callbacks
def update_representation(actor, mode):
    property = actor.GetProperty()
    if mode == Representation.Points:
        property.SetRepresentationToPoints()
        property.SetPointSize(5)
        property.EdgeVisibilityOff()
    elif mode == Representation.Wireframe:
        property.SetRepresentationToWireframe()
        property.SetPointSize(1)
        property.EdgeVisibilityOff()
    elif mode == Representation.Surface:
        property.SetRepresentationToSurface()
        property.SetPointSize(1)
        property.EdgeVisibilityOff()
    elif mode == Representation.SurfaceWithEdges:
        property.SetRepresentationToSurface()
        property.SetPointSize(1)
        property.EdgeVisibilityOn()


@state.change("mesh_representation")
def update_mesh_representation(mesh_representation, **kwargs):
    update_representation(mesh_actor, mesh_representation)
    ctrl.view_update()


@state.change("contour_representation")
def update_contour_representation(contour_representation, **kwargs):
    update_representation(contour_actor, contour_representation)
    ctrl.view_update()


# Color By Callbacks
def color_by_array(actor, array):
    _min, _max = array.get("range")
    mapper = actor.GetMapper()
    mapper.SelectColorArray(array.get("text"))
    mapper.GetLookupTable().SetRange(_min, _max)
    if array.get("type") == vtkDataObject.FIELD_ASSOCIATION_POINTS:
        mesh_mapper.SetScalarModeToUsePointFieldData()
    else:
        mesh_mapper.SetScalarModeToUseCellFieldData()
    mapper.SetScalarVisibility(True)
    mapper.SetUseLookupTableScalarRange(True)


@state.change("mesh_color_array_idx")
def update_mesh_color_by_name(mesh_color_array_idx, **kwargs):
    array = dataset_arrays[mesh_color_array_idx]
    color_by_array(mesh_actor, array)
    ctrl.view_update()


@state.change("contour_color_array_idx")
def update_contour_color_by_name(contour_color_array_idx, **kwargs):
    array = dataset_arrays[contour_color_array_idx]
    color_by_array(contour_actor, array)
    ctrl.view_update()


# Color Map Callbacks
def use_preset(actor, preset):
    lut = actor.GetMapper().GetLookupTable()
    if preset == LookupTable.Rainbow:
        lut.SetHueRange(0.666, 0.0)
        lut.SetSaturationRange(1.0, 1.0)
        lut.SetValueRange(1.0, 1.0)
    elif preset == LookupTable.Inverted_Rainbow:
        lut.SetHueRange(0.0, 0.666)
        lut.SetSaturationRange(1.0, 1.0)
        lut.SetValueRange(1.0, 1.0)
    elif preset == LookupTable.Greyscale:
        lut.SetHueRange(0.0, 0.0)
        lut.SetSaturationRange(0.0, 0.0)
        lut.SetValueRange(0.0, 1.0)
    elif preset == LookupTable.Inverted_Greyscale:
        lut.SetHueRange(0.0, 0.666)
        lut.SetSaturationRange(0.0, 0.0)
        lut.SetValueRange(1.0, 0.0)
    lut.Build()


@state.change("mesh_color_preset")
def update_mesh_color_preset(mesh_color_preset, **kwargs):
    use_preset(mesh_actor, mesh_color_preset)
    ctrl.view_update()


@state.change("contour_color_preset")
def update_contour_color_preset(contour_color_preset, **kwargs):
    use_preset(contour_actor, contour_color_preset)
    ctrl.view_update()


# Opacity Callbacks
@state.change("mesh_opacity")
def update_mesh_opacity(mesh_opacity, **kwargs):
    mesh_actor.GetProperty().SetOpacity(mesh_opacity)
    ctrl.view_update()


@state.change("contour_opacity")
def update_contour_opacity(contour_opacity, **kwargs):
    contour_actor.GetProperty().SetOpacity(contour_opacity)
    ctrl.view_update()


# Contour Callbacks
@state.change("contour_by_array_idx")
def update_contour_by(contour_by_array_idx, **kwargs):
    array = dataset_arrays[contour_by_array_idx]
    contour_min, contour_max = array.get("range")
    contour_step = 0.01 * (contour_max - contour_min)
    contour_value = 0.5 * (contour_max + contour_min)
    contour.SetInputArrayToProcess(0, 0, 0, array.get("type"), array.get("text"))
    contour.SetValue(0, contour_value)

    # Update UI
    state.contour_min = contour_min
    state.contour_max = contour_max
    state.contour_value = contour_value
    state.contour_step = contour_step

    # Update View
    ctrl.view_update()


@state.change("contour_value")
def update_contour_value(contour_value, **kwargs):
    contour.SetValue(0, float(contour_value))
    ctrl.view_update()


# -----------------------------------------------------------------------------
# GUI elements
# -----------------------------------------------------------------------------


def standard_buttons():
    vuetify.VCheckbox(
        v_model=("cube_axes_visibility", True),
        on_icon="mdi-cube-outline",
        off_icon="mdi-cube-off-outline",
        classes="mx-1",
        hide_details=True,
        dense=True,
    )
    vuetify.VCheckbox(
        v_model="$vuetify.theme.dark",
        on_icon="mdi-lightbulb-off-outline",
        off_icon="mdi-lightbulb-outline",
        classes="mx-1",
        hide_details=True,
        dense=True,
    )
    vuetify.VCheckbox(
        v_model=("viewMode", "local"),
        on_icon="mdi-lan-disconnect",
        off_icon="mdi-lan-connect",
        true_value="local",
        false_value="remote",
        classes="mx-1",
        hide_details=True,
        dense=True,
    )
    with vuetify.VBtn(icon=True, click="$refs.view.resetCamera()"):
        vuetify.VIcon("mdi-crop-free")


def pipeline_widget():
    return
    trame.GitTree(
        sources=(
            "pipeline",
            [
                {"id": "1", "parent": "0", "visible": 1, "name": "Mesh"},
                {"id": "2", "parent": "1", "visible": 1, "name": "Contour"},
            ],
        ),
        actives_change=(actives_change, "[$event]"),
        visibility_change=(visibility_change, "[$event]"),
    )


def ui_card(title, ui_name):
    with vuetify.VCard(v_show=f"active_ui == '{ui_name}'"):
        vuetify.VCardTitle(
            title,
            classes="grey lighten-1 py-1 grey--text text--darken-3",
            style="user-select: none; cursor: pointer",
            hide_details=True,
            dense=True,
        )
        content = vuetify.VCardText(classes="py-2")
    return content


def mesh_card():
    with ui_card(title="Mesh", ui_name="mesh"):
        vuetify.VSelect(
            # Representation
            v_model=("mesh_representation", Representation.Surface),
            items=(
                "representations",
                [
                    {"text": "Points", "value": 0},
                    {"text": "Wireframe", "value": 1},
                    {"text": "Surface", "value": 2},
                    {"text": "SurfaceWithEdges", "value": 3},
                ],
            ),
            label="Representation",
            hide_details=True,
            dense=True,
            outlined=True,
            classes="pt-1",
        )
        with vuetify.VRow(classes="pt-2", dense=True):
            with vuetify.VCol(cols="6"):
                vuetify.VSelect(
                    # Color By
                    label="Color by",
                    v_model=("mesh_color_array_idx", 0),
                    items=("array_list", dataset_arrays),
                    hide_details=True,
                    dense=True,
                    outlined=True,
                    classes="pt-1",
                )
            with vuetify.VCol(cols="6"):
                vuetify.VSelect(
                    # Color Map
                    label="Colormap",
                    v_model=("mesh_color_preset", LookupTable.Rainbow),
                    items=(
                        "colormaps",
                        [
                            {"text": "Rainbow", "value": 0},
                            {"text": "Inv Rainbow", "value": 1},
                            {"text": "Greyscale", "value": 2},
                            {"text": "Inv Greyscale", "value": 3},
                        ],
                    ),
                    hide_details=True,
                    dense=True,
                    outlined=True,
                    classes="pt-1",
                )
        vuetify.VSlider(
            # Opacity
            v_model=("mesh_opacity", 1.0),
            min=0,
            max=1,
            step=0.1,
            label="Opacity",
            classes="mt-1",
            hide_details=True,
            dense=True,
        )


def contour_card():
    with ui_card(title="Contour", ui_name="contour"):
        vuetify.VSelect(
            # Contour By
            label="Contour by",
            v_model=("contour_by_array_idx", 0),
            items=("array_list", dataset_arrays),
            hide_details=True,
            dense=True,
            outlined=True,
            classes="pt-1",
        )
        vuetify.VSlider(
            # Contour Value
            v_model=("contour_value", contour_value),
            min=("contour_min", default_min),
            max=("contour_max", default_max),
            step=("contour_step", 0.01 * (default_max - default_min)),
            label="Value",
            classes="my-1",
            hide_details=True,
            dense=True,
        )
        vuetify.VSelect(
            # Representation
            v_model=("contour_representation", Representation.Surface),
            items=(
                "representations",
                [
                    {"text": "Points", "value": 0},
                    {"text": "Wireframe", "value": 1},
                    {"text": "Surface", "value": 2},
                    {"text": "SurfaceWithEdges", "value": 3},
                ],
            ),
            label="Representation",
            hide_details=True,
            dense=True,
            outlined=True,
            classes="pt-1",
        )
        with vuetify.VRow(classes="pt-2", dense=True):
            with vuetify.VCol(cols="6"):
                vuetify.VSelect(
                    # Color By
                    label="Color by",
                    v_model=("contour_color_array_idx", 0),
                    items=("array_list", dataset_arrays),
                    hide_details=True,
                    dense=True,
                    outlined=True,
                    classes="pt-1",
                )
            with vuetify.VCol(cols="6"):
                vuetify.VSelect(
                    # Color Map
                    label="Colormap",
                    v_model=("contour_color_preset", LookupTable.Rainbow),
                    items=(
                        "colormaps",
                        [
                            {"text": "Rainbow", "value": 0},
                            {"text": "Inv Rainbow", "value": 1},
                            {"text": "Greyscale", "value": 2},
                            {"text": "Inv Greyscale", "value": 3},
                        ],
                    ),
                    hide_details=True,
                    dense=True,
                    outlined=True,
                    classes="pt-1",
                )
        vuetify.VSlider(
            # Opacity
            v_model=("contour_opacity", 1.0),
            min=0,
            max=1,
            step=0.1,
            label="Opacity",
            classes="mt-1",
            hide_details=True,
            dense=True,
        )


# -----------------------------------------------------------------------------
# GUI
# -----------------------------------------------------------------------------

with SinglePageWithDrawerLayout(server) as layout:
    layout.title.set_text("Viewer")

    with layout.toolbar:
        # toolbar components
        vuetify.VSpacer()
        vuetify.VDivider(vertical=True, classes="mx-2")
        standard_buttons()

    with layout.drawer as drawer:
        # drawer components
        drawer.width = 325
        pipeline_widget()
        vuetify.VDivider(classes="mb-2")
        mesh_card()
        contour_card()

    with layout.content:
        # content components
        with vuetify.VContainer(
            fluid=True,
            classes="pa-0 fill-height",
        ):
            # view = vtk.VtkRemoteView(renderWindow, interactive_ratio=1)
            # view = vtk.VtkLocalView(renderWindow)
            view = vtk.VtkRemoteLocalView(
                 renderWindow, namespace="view", mode="local", interactive_ratio=1
             )
            ctrl.view_update = view.update
            ctrl.view_reset_camera = view.reset_camera

```

**Expected behavior**

Render in remote view is shown inside the webpage, memory usage is stable and proportional to the vtk data.

**Screenshots**

https://github.com/Kitware/trame/assets/3021667/48d1489c-552a-45c9-a89d-96b8a8e45339

Please note that when using the Remote view, nothing is displayed.
Another window pops-up when starting with right rendering, but the interactor doesn't work (I bet this is expected).
RAM grows indefinitely. It's like new renderers are added continuously, the size of the increases are constant. 
The wslink is broken since the start, the console displays:
```txt
App running at:
 - Local:   http://localhost:8080/
 - Network: http://127.0.0.1:8080/

Note that for multi-users you need to use and configure a launcher.
And to prevent your browser from opening, add '--server' to your command line.
Opening in existing browser session.
Task exception was never retrieved
future: <Task finished name='Task-86' coro=<WslinkHandler.sendWrappedMessage() done, defined at /path/lib/python3.9/site-packages/wslink/protocol.py:423> exception=ConnectionResetError('Cannot write to closing transport')>
Traceback (most recent call last):
  File "/path/lib/python3.9/site-packages/wslink/protocol.py", line 475, in sendWrappedMessage
    await ws.send_str(json_header)
  File "/path/lib/python3.9/site-packages/aiohttp/web_ws.py", line 335, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/path/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 729, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/path/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 682, in _send_frame
    self._write(header + message)
  File "/path/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 702, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport
Exception raised
ConnectionResetError('Cannot write to closing transport')
Traceback (most recent call last):
  File "/path/lib/python3.9/site-packages/wslink/protocol.py", line 340, in onMessage
    await self.sendWrappedMessage(
  File "/path/lib/python3.9/site-packages/wslink/protocol.py", line 484, in sendWrappedMessage
    await ws.send_str(encMsg)
  File "/path/lib/python3.9/site-packages/aiohttp/web_ws.py", line 335, in send_str
    await self._writer.send(data, binary=False, compress=compress)
  File "/path/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 729, in send
    await self._send_frame(message, WSMsgType.TEXT, compress)
  File "/path/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 682, in _send_frame
    self._write(header + message)
  File "/path/lib/python3.9/site-packages/aiohttp/http_websocket.py", line 702, in _write
    raise ConnectionResetError("Cannot write to closing transport")
ConnectionResetError: Cannot write to closing transport

```
This is the log with `TRAME_LOG_NETWORK=./log.log` (other session that the one recorded, only with vtkRemoteView)
[log.log](https://github.com/Kitware/trame/files/14551854/log.log)
It seems that many calls to addRenderer?

These are with python 3.11, but I tried with python3.9, and same behavior. 
Paraview 5.12 binary works fine.

**Platform:**

***Device:***

- [x] Desktop
- [ ] Mobile

***OS:***

- [ ] Windows
- [ ] MacOS
- [x] Linux. kernel 6.7.9.arch1-1, cuda 12.4.0-2
- [ ] Android
- [ ] iOS

***Browsers Affected:***

- [ ] Chrome
- [ ] Firefox
- [ ] Microsoft Edge
- [ ] Safari
- [ ] Opera
- [x] Brave
- [ ] IE 11

**Comment by jourdain** [comment]
Thanks for the detailed issue. But I've just tested the code on a fresh venv and it is working fine on my mac.
I do see the memory grow and shrink as expected.

Can you provide the versions of your various packages (`pip list`)?

My setup was

```
Package             Version
------------------- -----------
aiohttp             3.9.3
aiosignal           1.3.1
async-timeout       4.0.3
attrs               23.2.0
contourpy           1.2.0
cycler              0.12.1
fonttools           4.49.0
frozenlist          1.4.1
idna                3.6
importlib_resources 6.1.3
kiwisolver          1.4.5
matplotlib          3.8.3
more-itertools      10.2.0
multidict           6.0.5
numpy               1.26.4
packaging           24.0
pillow              10.2.0
pip                 24.0
pyparsing           3.1.2
python-dateutil     2.9.0.post0
setuptools          65.4.1
six                 1.16.0
trame               3.5.2
trame-client        2.16.2
trame-server        2.17.2
trame-vtk           2.8.5
trame-vuetify       2.4.2
vtk                 9.3.0
wslink              1.12.4
yarl                1.9.4
zipp                3.17.0
```

**Comment by phcerdan** [comment]
Maybe something cuda or linux specific?

python 3.11
```
Package         Version
--------------- -----------
aiohttp         3.9.3
aiosignal       1.3.1
attrs           23.2.0
build           1.1.1
click           8.1.7
contourpy       1.2.0
cycler          0.12.1
distro          1.9.0
fonttools       4.49.0
frozenlist      1.4.1
idna            3.6
kiwisolver      1.4.5
matplotlib      3.8.3
more-itertools  10.2.0
multidict       6.0.5
numpy           1.26.4
packaging       23.2
pillow          10.2.0
pip             24.0
pip-tools       7.4.1
pyparsing       3.1.2
pyproject_hooks 1.0.0
python-dateutil 2.9.0.post0
scikit-build    0.17.6
setuptools      65.5.0
six             1.16.0
trame           3.5.2
trame-client    2.16.2
trame-server    2.17.2
trame-vtk       2.8.5
trame-vuetify   2.4.2
vtk             9.3.0
wheel           0.42.0
wslink          1.12.4
yarl            1.9.4
```

**Comment by phcerdan** [comment]
Any suggestion to try to debug it would be welcome. I have no idea where to start going deeper. Maybe something wslink related?

**Comment by jourdain** [comment]
When you [download ParaView](https://www.paraview.org/download), does it render and work as expected?
What do you get in the about dialog?

<img width="662" alt="Screenshot 2024-03-11 at 11 14 50" src="https://github.com/Kitware/trame/assets/294518/ae1a7187-0365-49cf-9484-07052c0ad006">

**Comment by phcerdan** [comment]
![image](https://github.com/Kitware/trame/assets/3021667/d69640e8-807e-4a9a-bf66-52c1b55ebaa2)

> Also can you also try with Python 3.9 or 3.10?

> These are with python 3.11, but I tried with python3.9, and same behavior.

I tried with both (via conda)

**Comment by phcerdan** [comment]
Found it...

If I use gnome, instead of i3, as window manager, it works...

i3 doesn't show the name of the windows. How is the transfer of the render window to the webpage done?

**Comment by jourdain** [comment]
VTK grabs the pixels of its render window before sending them. And I was suspecting that step was failing and sending garbage over the wire...

**Comment by phcerdan** [comment]
Should I open an issue in VTK proper then?
I would like to keep using i3 as windows manager.

**Comment by jourdain** [comment]
Yes, please, especially since it seems to be related to that window manager. Unless you want to try to use `vtk-egl`, which may solve that window manager issue. 

Just make sure you remove any vtk previously installed in your venv. (`pip install --extra-index-url https://wheels.vtk.org vtk-egl`)

**Comment by phcerdan** [comment]
vtk-egl works indeed.

Could you aid me with the title for the VTK issue? What vtk class manages the "transfer"? I am not sure how to describe the problem in VTK terms.

**Comment by jourdain** [comment]
So the main issue is the window creation. Does the problem show up with ParaView as well? 

Ideally, you want to find an example that highlights such an issue. One simple [VTK Python example](https://examples.vtk.org/site/Python/GeometricObjects/CylinderExample/) (assuming it fails) might be enough.

**Comment by phcerdan** [comment]
I have no problem creating vtk windows. The problem seems when transferring the content of the render window into the webpage.
With vtkRemoteView nothing is displayed in the webpage, but the window is created and displays fine.

**Comment by jourdain** [comment]
Can you try that python example and see if it fails producing the image on disk?
https://examples.vtk.org/site/Python/Utilities/Screenshot/

**Comment by phcerdan** [comment]
> Can you try that python example and see if it fails producing the image on disk?

Tried, and it works fine. TestScreenshot.png is created 
![image](https://github.com/Kitware/trame/assets/3021667/35f75115-f2b6-404a-bc3d-47450c13e860)

**Comment by jourdain** [comment]
Sorry to keep asking you to try things out, but I'm wondering if you call `renderWindow.SetOffScreenRendering(1)`, that fix the trame remote view issue.

**Comment by phcerdan** [comment]
That fixes it as well.

Was that a requirement for using VtkRemoteView?

**Comment by jourdain** [comment]
It should not be a requirement, but technically, there is no point in showing the window on the server. When using an offscreen flavor like egl/osmesa, this implicit automatic. On a graphic/desktop environment, that is another story, and it should be up to the user/dev to decide if they want to call such a function. In your case, it seems that the window manager mess things up somewhere in the process so forcing an offscreen window is required. 

I think the best way forward would be to document that, but I'm not sure how to best describe and capture the reader attention. Any suggestion or PR on doc update is welcome... 

Thanks for tracking that down.
