### ISSUE TITLE
"Exception: no view provided: -1" on trame 1.19.1

### ISSUE THREAD

**Issue by DavidBerger98** [Kitware/trame#57]
**Describe the bug**

On the latest version of `trame` (1.19.1), the VTK view does not work as on version 1.18.0. The viewer doesn't show up in the UI and I am getting an error from `vtkmodules` saying: 

```
ERROR:root:Exception raised
ERROR:root:Exception('no view provided: -1')
ERROR:root:Traceback (most recent call last):
  File ".../lib/python3.8/site-packages/wslink/backends/aiohttp/__init__.py", line 371, in onMessage
    results = await asyncio.coroutine(func)(*args, **kwargs)
  File "/usr/lib/python3.8/asyncio/coroutines.py", line 124, in coro
    res = func(*args, **kw)
  File ".../lib/python3.8/site-packages/vtkmodules/web/protocols.py", line 425, in imagePush
    sView = self.getView(options["view"])
  File ".../lib/python3.8/site-packages/vtkmodules/web/protocols.py", line 80, in getView
    raise Exception("no view provided: %s" % vid)
Exception: no view provided: -1
```

I think it may be because of this commit? https://github.com/Kitware/trame/commit/ad23c4d88884319c05391b7e195cd8bcc85f9738

**To Reproduce**

Minimal code to reproduce:

```python
import vtk
from trame import change, state
from trame.layouts import SinglePageWithDrawer
from trame.html import vuetify
from trame.html.vtk import VtkRemoteLocalView

# -----------------------------------------------------------------------------
# VTK pipeline
# -----------------------------------------------------------------------------

renderer = vtk.vtkRenderer()
renderWindow = vtk.vtkRenderWindow()
renderWindow.AddRenderer(renderer)

renderWindowInteractor = vtk.vtkRenderWindowInteractor()
renderWindowInteractor.SetRenderWindow(renderWindow)
renderWindowInteractor.GetInteractorStyle().SetCurrentStyleToTrackballCamera()

# -----------------------------------------------------------------------------
# Callbacks
# -----------------------------------------------------------------------------
@change("viewMode")
def update_view(viewMode, flush=True, **kwargs):
    html_view.update_image()
    if viewMode == "local":
        html_view.update_geometry()
        if flush:
            # can only flush once protocol is initialized (publish)
            state.flush("viewScene")

# -----------------------------------------------------------------------------
# GUI
# -----------------------------------------------------------------------------

html_view = VtkRemoteLocalView(renderWindow, namespace="view")

def on_ready(**kwargs):
    update_view("local", flush=False)
    html_view.update()
    renderer.ResetCamera()

layout = SinglePageWithDrawer("Trame App", on_ready=on_ready)

with layout.content:
    vuetify.VContainer(
        fluid=True,
        classes="pa-0 fill-height",
        children=[html_view],
    )

if __name__ == "__main__":
    layout.start()
```

**Comment by jourdain** [comment]
Browser cache issue. Just clear your cache.

**Comment by jourdain** [comment]
Actually when you update `trame` you also need to update `pywebvue`.
